# Pandas para Data Science
Pandas es una librería orientada al análisis y procesamiento de datos. El objeto básico de datos de Pandas es un DataFrame.

In [ ]:
import pandas as pd

## Creación de un Data Frame
### A partir de un arreglo de datos (lista, diccionario, tupla)

In [ ]:
a = ['a','b','c']

In [ ]:

dataframe = pd.DataFrame(a)
dataframe

### A partir de un archivo 
* excel
* csv: coma separated value
* tsv: tab separated value
* json: javascript object notation

largo etc...

In [ ]:
dataframe2 = pd.read_csv('ejemplo.csv')

In [ ]:
dataframe2

### De un endpoint en internet

In [44]:
import json
import requests

In [45]:
endpoint = 'https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv'

In [46]:
dataframe = pd.read_csv(endpoint)

In [47]:
dataframe

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,...,2020-06-28,2020-07-01,2020-07-05,2020-07-10,2020-07-13,2020-07-17,2020-07-20,2020-07-24,2020-07-27,Tasa
0,Arica y Parinacota,15,Arica,15101.0,247552.0,6.0,6.0,12.0,41.0,63.0,...,1758.0,1887.0,2139.0,2464.0,2721.0,3123.0,3372.0,3882.0,4211.0,1701.1
1,Arica y Parinacota,15,Camarones,15102.0,1233.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,13.0,13.0,13.0,15.0,1216.5
2,Arica y Parinacota,15,General Lagos,15202.0,810.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,123.5
3,Arica y Parinacota,15,Putre,15201.0,2515.0,0.0,0.0,0.0,0.0,0.0,...,11.0,11.0,11.0,26.0,28.0,28.0,30.0,36.0,37.0,1471.2
4,Arica y Parinacota,15,Desconocido Arica y Parinacota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,1.0,3.0,3.0,3.0,5.0,5.0,6.0,6.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Magallanes,12,Rio Verde,12103.0,211.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
358,Magallanes,12,San Gregorio,12104.0,681.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,293.7
359,Magallanes,12,Timaukel,12303.0,282.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
360,Magallanes,12,Torres del Paine,12402.0,1021.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
361,Magallanes,12,Desconocido Magallanes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68.0,68.0,68.0,70.0,70.0,70.0,70.0,70.0,70.0,NaN

## Seleccionar Datos

**Por columnas**

In [48]:
dataframe['Region'][0:3]

0    Arica y Parinacota
1    Arica y Parinacota
2    Arica y Parinacota
Name: Region, dtype: object

**Por Filas**

In [ ]:
dataframe.iloc[3]

**Un valor en particular**

In [ ]:
dataframe.iloc[3,1]

### Seleccionar datos según valores 
Qué hacemos si queremos seleccionar solo los datos de una comuna

In [49]:
dataframe.loc[(dataframe['Region']=='Arica y Parinacota')]

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,...,2020-06-28,2020-07-01,2020-07-05,2020-07-10,2020-07-13,2020-07-17,2020-07-20,2020-07-24,2020-07-27,Tasa
0,Arica y Parinacota,15,Arica,15101.0,247552.0,6.0,6.0,12.0,41.0,63.0,...,1758.0,1887.0,2139.0,2464.0,2721.0,3123.0,3372.0,3882.0,4211.0,1701.1
1,Arica y Parinacota,15,Camarones,15102.0,1233.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,13.0,13.0,13.0,15.0,1216.5
2,Arica y Parinacota,15,General Lagos,15202.0,810.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,123.5
3,Arica y Parinacota,15,Putre,15201.0,2515.0,0.0,0.0,0.0,0.0,0.0,...,11.0,11.0,11.0,26.0,28.0,28.0,30.0,36.0,37.0,1471.2
4,Arica y Parinacota,15,Desconocido Arica y Parinacota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,1.0,3.0,3.0,3.0,5.0,5.0,6.0,6.0,NaN

In [50]:
dataframe.loc[(dataframe['Region']=='Arica y Parinacota') & (dataframe['Poblacion']>1000)]

,Region,Codigo region,Comuna,Codigo comuna,Poblacion,2020-03-30,2020-04-01,2020-04-03,2020-04-06,2020-04-08,...,2020-06-28,2020-07-01,2020-07-05,2020-07-10,2020-07-13,2020-07-17,2020-07-20,2020-07-24,2020-07-27,Tasa
0,Arica y Parinacota,15,Arica,15101.0,247552.0,6.0,6.0,12.0,41.0,63.0,...,1758.0,1887.0,2139.0,2464.0,2721.0,3123.0,3372.0,3882.0,4211.0,1701.1
1,Arica y Parinacota,15,Camarones,15102.0,1233.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,13.0,13.0,13.0,15.0,1216.5
3,Arica y Parinacota,15,Putre,15201.0,2515.0,0.0,0.0,0.0,0.0,0.0,...,11.0,11.0,11.0,26.0,28.0,28.0,30.0,36.0,37.0,1471.2

Pero si solo queremos los infectados y  no el resto de los valores?

In [ ]:
dataframe.loc[dataframe['Comuna']=='Santiago'].iloc[:,5:-1]

Y si quieremos sumar todos los datos de una región? Se les ocurre?

### Por el valor de los datos

In [ ]:
endpoint = 'https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv'
aux = pd.read_csv(endpoint)        
I_ac_r = aux.loc[aux['Codigo region']==int(self.tstate)].iloc[:,5:-1].sum()

    self.I_ac_r_dates = [datetime.strptime(self.I_ac_r.index[i],'%Y-%m-%d') for i in range(len(self.I_ac_r))]
    index = np.where(np.array(self.I_ac_r_dates) >= self.initdate)[0][0] 
    self.I_ac_r = self.I_ac_r[index:]
    self.I_ac_r_dates = self.I_ac_r_dates[index:]
    self.I_ac_r_tr = [(self.I_ac_r_dates[i]-self.initdate).days for i in range(len(self.I_ac_r))]
    print('Infectados Acumulados')

# Agregar Datos

## Agregar Filas
Agregar elementos (filas) al final del dataframe en el dataframe,conservando las mismas columnas existentes, se puede hacer de varias formas.
La forma más sencilla es la siguiente:  
```  dataframe.loc[i] = [data] ```   
Donde:
* **dataframe**: Es tu dataframe =)
* **i** es el número de fila que quieres modificar o es una más abajo de la última para agregar una nueva
* **data** es la data que quieres agregar, la cual tiene que tener la misma estructura del dataframe (la misma cantidad de columnas)

## Agregar Columnas
Para agregar una nueva columna existe el comando insert que tiene la siguiente estructura:
```datafframe.insert(loc,nombrecolumna,valores)```
Donde: 
* **dataframe**: Es tu dataframe =)
* **loc** es la posición donde se agregará la nueva columna
* **nombrecolumna** es el nombre de la columna
* **valores** es la data que quieres agregar, la cual tiene que tener la misma estructura del dataframe (la misma cantidad de filas)